# Generated by Django 2.2.19 on 2022-04-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
