# Generated by Django 2.2.19 on 2022-04-21 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials_base', '0002_auto_20220417_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
